# Generated by Django 5.0.4 on 2024-04-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
